import {google} from 'googleapis';
import {loadProviderToken,saveProviderToken} from './tokens.js';
const SCOPES=['openid','email','https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/gmail.modify','https://www.googleapis.com/auth/calendar'];
export function googleConfigured(){return Boolean(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET);}
function redirectUri(){return process.env.GOOGLE_REDIRECT_URI||`${process.env.APP_URL||''}/api/oauth/google/callback`;}
function assertConfigured(){if(!googleConfigured()){const e=new Error('Google needs GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in Vercel Environment Variables');e.status=409;throw e;}}
function oauth(){assertConfigured();return new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,redirectUri());}
export function googleAuthUrl(state){return oauth().generateAuthUrl({access_type:'offline',prompt:'consent',include_granted_scopes:true,scope:SCOPES,state});}
export async function googleExchange(code){const c=oauth();const {tokens}=await c.getToken(code);c.setCredentials(tokens);const info=await google.oauth2({version:'v2',auth:c}).userinfo.get();const allowed=(process.env.GOOGLE_ALLOWED_EMAIL||'greg@arborwisetreecare.com').toLowerCase();if(allowed&&String(info.data.email||'').toLowerCase()!==allowed)throw new Error('This Google account is not authorized for Arborwise OS');return {access_token:tokens.access_token,refresh_token:tokens.refresh_token,expires_at:tokens.expiry_date?new Date(tokens.expiry_date):null,metadata:{email:info.data.email}};}
export async function googleClient(){const stored=await loadProviderToken('google');if(!stored){const e=new Error('Google is not authorized yet. Open Connections and tap Connect Google.');e.status=409;throw e;}const c=oauth();c.setCredentials({access_token:stored.access_token,refresh_token:stored.refresh_token,expiry_date:stored.expires_at?new Date(stored.expires_at).getTime():undefined});c.on('tokens',async t=>{if(t.access_token||t.refresh_token)await saveProviderToken('google',{access_token:t.access_token||stored.access_token,refresh_token:t.refresh_token||stored.refresh_token,expires_at:t.expiry_date?new Date(t.expiry_date):stored.expires_at,metadata:stored.metadata||{}})});return c;}
function rowsToObjects(values=[]){const [headers=[], ...rows]=values;return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(headers.map((h,i)=>[String(h||'').trim(),r[i]??''])));}
export async function sheetRows(tab,range='A:AA'){const auth=await googleClient();const sheets=google.sheets({version:'v4',auth});const r=await sheets.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID||'17XTUBhP7zC01qc6aNavMYCoFBEsnE9wUvmMmd-5lt1w',range:`'${tab}'!${range}`});return rowsToObjects(r.data.values||[]);}
export async function googleSyncData(){const auth=await googleClient();const [master,jobs,today]=await Promise.all([sheetRows('Master Estimates'),sheetRows('Jobs','A:U'),sheetRows("Today's Estimates")]);const gmail=google.gmail({version:'v1',auth});const list=await gmail.users.messages.list({userId:'me',q:'newer_than:3d -category:promotions',maxResults:100});const messages=[];for(const m of (list.data.messages||[]).slice(0,50)){const g=await gmail.users.messages.get({userId:'me',id:m.id,format:'metadata',metadataHeaders:['From','Subject','Date']});const h=Object.fromEntries((g.data.payload?.headers||[]).map(x=>[x.name,x.value]));messages.push({id:m.id,threadId:g.data.threadId,from:h.From||'',subject:h.Subject||'',date:h.Date||'',snippet:g.data.snippet||'',labelIds:g.data.labelIds||[]});}const cal=google.calendar({version:'v3',auth});const events=(await cal.events.list({calendarId:'primary',timeMin:new Date().toISOString(),timeMax:new Date(Date.now()+14*86400000).toISOString(),singleEvents:true,orderBy:'startTime',maxResults:250})).data.items||[];return {master,jobs,today,messages,events};}
